import './js/refs/refs';
import './js/localStorage/lsService';
import './js/components/animations';
import './js/components/header-on-scroll';
import './js/components/navigation';
import './js/components/mobile-menu';
import './js/components/list-on-scroll';
import './js/components/to-top-button';
import './js/components/slider';
import './js/components/hidden-text';
import './js/components/testimonialsOfClients';
import './js/components/getSubtitleOfAudio';
import './js/components/player';
import './js/components/getBgcServices';
// import './js/functions/audio-player';
import './js/functions/subtitels';
import './js/functions/animation';
// import './js/functions/scroll-left-and-right';
